import type { Scenario } from "./types";

export const SCENARIOS: Scenario[] = [
  {
    id: "prior-auth",
    title: "Prior authorization check",
    description: "Healthcare AI agent validating a drug authorization request",
    userPrompt: "Evaluate prior authorization for Adalimumab for patient with Rheumatoid Arthritis on Commercial PPO plan",
    tools: [
      {
        id: "get_patient_history",
        name: "get_patient_history",
        description: "Fetch patient's prior diagnoses, failed therapies, and prior auth history from EHR",
        category: "data",
        dependsOn: [],
        simulatedMs: 820,
      },
      {
        id: "check_formulary",
        name: "check_formulary",
        description: "Look up drug tier, step therapy requirements, and formulary coverage for the plan",
        category: "data",
        dependsOn: [],
        simulatedMs: 560,
      },
      {
        id: "validate_coverage",
        name: "validate_coverage",
        description: "Validate patient's current plan, deductible status, and network tier",
        category: "data",
        dependsOn: [],
        simulatedMs: 690,
      },
      {
        id: "check_drug_interactions",
        name: "check_drug_interactions",
        description: "Cross-reference requested drug against patient's current medications",
        category: "compute",
        dependsOn: ["get_patient_history", "check_formulary"],
        simulatedMs: 410,
      },
      {
        id: "evaluate_step_therapy",
        name: "evaluate_step_therapy",
        description: "Determine if step therapy requirements are met based on prior treatment history",
        category: "compute",
        dependsOn: ["get_patient_history", "check_formulary"],
        simulatedMs: 380,
      },
      {
        id: "generate_pa_decision",
        name: "generate_pa_decision",
        description: "Synthesize all findings into an APPROVED / DENIED / PENDING decision with rationale",
        category: "compute",
        dependsOn: ["check_drug_interactions", "evaluate_step_therapy", "validate_coverage"],
        simulatedMs: 290,
      },
    ],
  },
  {
    id: "arch-review",
    title: "Architecture review agent",
    description: "AI agent auditing a microservices codebase for latency and resilience issues",
    userPrompt: "Review the payment service architecture for latency bottlenecks and resilience gaps",
    tools: [
      {
        id: "read_service_manifest",
        name: "read_service_manifest",
        description: "Read service definitions, dependencies, and deployment config from repo",
        category: "data",
        dependsOn: [],
        simulatedMs: 440,
      },
      {
        id: "fetch_trace_data",
        name: "fetch_trace_data",
        description: "Pull last 7 days of distributed traces from observability platform",
        category: "external",
        dependsOn: [],
        simulatedMs: 1100,
      },
      {
        id: "fetch_error_rates",
        name: "fetch_error_rates",
        description: "Retrieve p50/p99 latency and error rates per endpoint from metrics store",
        category: "external",
        dependsOn: [],
        simulatedMs: 780,
      },
      {
        id: "analyze_dependencies",
        name: "analyze_dependencies",
        description: "Map synchronous call chains and identify circular dependencies",
        category: "compute",
        dependsOn: ["read_service_manifest", "fetch_trace_data"],
        simulatedMs: 620,
      },
      {
        id: "identify_bottlenecks",
        name: "identify_bottlenecks",
        description: "Correlate trace data with error rates to pinpoint p99 latency culprits",
        category: "compute",
        dependsOn: ["fetch_trace_data", "fetch_error_rates"],
        simulatedMs: 540,
      },
      {
        id: "write_adr",
        name: "write_adr",
        description: "Generate a structured Architecture Decision Record with findings and recommendations",
        category: "write",
        dependsOn: ["analyze_dependencies", "identify_bottlenecks"],
        simulatedMs: 310,
      },
    ],
  },
  {
    id: "incident-response",
    title: "Incident response agent",
    description: "AI agent triaging a production latency spike at market open",
    userPrompt: "Production latency spike detected on FX pricing service — triage and recommend immediate action",
    tools: [
      {
        id: "pull_recent_logs",
        name: "pull_recent_logs",
        description: "Fetch last 15 minutes of error logs from the affected service",
        category: "data",
        dependsOn: [],
        simulatedMs: 650,
      },
      {
        id: "check_deployment_history",
        name: "check_deployment_history",
        description: "Check for recent deployments or config changes in the past 2 hours",
        category: "data",
        dependsOn: [],
        simulatedMs: 390,
      },
      {
        id: "query_metrics",
        name: "query_metrics",
        description: "Pull CPU, memory, GC pause times, and thread pool saturation metrics",
        category: "external",
        dependsOn: [],
        simulatedMs: 870,
      },
      {
        id: "correlate_events",
        name: "correlate_events",
        description: "Cross-correlate log errors with deployment events and metric anomalies",
        category: "compute",
        dependsOn: ["pull_recent_logs", "check_deployment_history", "query_metrics"],
        simulatedMs: 470,
      },
      {
        id: "identify_root_cause",
        name: "identify_root_cause",
        description: "Apply pattern matching against known failure modes to identify root cause",
        category: "compute",
        dependsOn: ["correlate_events"],
        simulatedMs: 350,
      },
      {
        id: "draft_runbook_action",
        name: "draft_runbook_action",
        description: "Generate an immediate remediation action with rollback steps if needed",
        category: "write",
        dependsOn: ["identify_root_cause"],
        simulatedMs: 280,
      },
    ],
  },
];

export const SCENARIO_MAP = Object.fromEntries(SCENARIOS.map((s) => [s.id, s]));
